[functions]
  external_node_modules = ["express"]
  [functions.inluded_files]
    inluded_files = [
      "views/*/*.hbs",
      "views/*.hbs"
    ]
  node_bundler = "esbuild"
[build]
  functions = "src"  
[[redirects]]
  force = true
  from = "/*"
  status = 200
  to = "/.netlify/functions/app/:splat"
